version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:1.28.1
    container_name: vaultwarden
    restart: always
    environment:
      WEBSOCKET_ENABLED: "true"  # Enable WebSocket notifications.
    volumes:
      - ./vw-data:/data
    ports:
      - 3012:3012
      - 13464:80
