version: '3'

services:

  web:
    image: 'gitlab/gitlab-ce:15.10.2-ce.0'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:11261'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '11261:11261'
      - '2224:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
