version: '3'

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-docker-certs: {}
  jenkins-docker-certs: {}

services:

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-docker-certs:/var/jenkins_home
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    restart: always
    ports:
      - 2376:2376
    networks:
      jenkins:
        aliases:
          - docker

  jenkins-blueocean:
    image: myjenkins-blueocean:2.399
    container_name: jenkins-blueocean
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-docker-certs:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    restart: on-failure
    ports:
      - 38080:8080
      - 50000:50000
    networks:
      - jenkins
